package io.openems.edge.smartsolarbox.modbus;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Smart Solar Box Modbus", //
		description = "This component consists of all data related to Smart Solar Box Modbus.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "SmartSolarBoxModbus0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";
	
	@AttributeDefinition(name = "Log File", description = "File consisting of the solar logs")
	String logFile() default "io.openems.edge.smartsolarbox.modbus/log/smartsolar/solarlog.log";
	
	@AttributeDefinition(name = "Device", description = "Path of the device to be used")
	String device() default "/dev/ttyXRUSB0";
	
	String webconsole_configurationFactory_nameHint() default "Smart Solar Box Modbus [{id}]";

}